// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		int num = Integer.parseInt(args[0]);
		double result;
		double countSmall = 0;
		double countBig = 0;
		for (int i = 0; i < num; i++) {
			result = Math.random();
			if (result > 0.5) {
				countBig++;
			} else {
				countSmall++;
			}

		}

		System.out.println((countBig != 0 && countSmall != 0) ? "Ratio: " + countBig / countSmall : "");

	}
}
